project:
  type: book
  output-dir: outputs/reports

book:
  title: "County-Level Spatial Graph Modeling of Social Vulnerability and FEMA Disaster Assistance (2018–2020)"
  author: "UC Irvine/Machine Learning & Data Mining: Joe Nguyen, Jared Lyon, Haesung Becker"
  chapters:
    - index.qmd
    - notebooks\01_eda.qmd
    - notebooks\02_mlp.qmd
    - notebooks\03_gcn.qmd
    - notebooks\04_conclusion.qmd
format:
  pdf:
    output-file: svi_fema_2018_2020_report.pdf
    fig-path: outputs/figures
    fontsize: 10pt
    fig-width: 2
    fig-height: 2
    dpi: 300
    number-sections: true
    toc: true
    toc-depth: 3
    df-print: default
    keep-tex: true
    fig-pos: "H"
    tbl-pos: "H"
    highlight-style: github
    geometry:
      - margin=0.75in
    header-includes:
      - \KOMAoption{captions}{tableheading}
      - \KOMAoption{headings}{normal}
      - \usepackage{textcomp}
      - \usepackage{fancyvrb}
      - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
      - \RedeclareSectionCommand[beforeskip=0pt,afterskip=1.2\baselineskip]{chapter}
    include-in-header:
      text: |
        \usepackage{float}
        \usepackage[section]{placeins}
        \usepackage{multirow}
        \usepackage{booktabs}
        \usepackage{adjustbox}

execute:
  echo: false
  warning: false
  message: false
  freeze: false
  error: true
    