# Conclusion

## Project Contributions


## Challenges & Limitations


## Future Work


# References

1) Centers for Disease Control and Prevention/Agency for Toxic Substances and Disease Registry. (2024). A validity assessment of the Centers for Disease Control and Prevention/Agency for Toxic Substances and Disease Registry Social Vulnerability Index (CDC/ATSDR SVI). U.S. Department of Health and Human Services. 

2) Federal Emergency Management Agency. (2020). COVID-19 pandemic: Emergency declaration under the Stafford Act. https://www.fema.gov
   
3) Federal Emergency Management Agency. (n.d.). Disaster declarations summaries (v2). OpenFEMA. https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2
   
4) Flanagan, B. E., Gregory, E. W., Hallisey, E. J., Heitgerd, J. L., & Lewis, B. (2011). A social vulnerability index for disaster management. Journal of Homeland Security and Emergency Management, 8(1), Article 3.

5) Kalaycioglu, O., Akhanli, S. E., Mentese, E. Y., Kalaycioglu, M., & Kalaycioglu, S. (n.d.). Using machine learning algorithms to identify predictors of social vulnerability in the event of a hazard: Istanbul case study. 

6) Kipf, T. N., & Welling, M. (2017). Semi-supervised classification with graph convolutional networks. In International Conference on Learning Representations (ICLR). https://arxiv.org/abs/1609.02907

7) Tarling, H. A. (2017). Comparative analysis of social vulnerability indices: CDC's SVI and SoVI® [Master's thesis, Lund University].

7) Robert T. Stafford Disaster Relief and Emergency Assistance Act, 42 U.S.C. §§ 5121–5207 (1988).

9) Veličković, P., Cucurull, G., Casanova, A., Romero, A., Liò, P., & Bengio, Y. (2018). Graph attention networks. In International Conference on Learning Representations (ICLR). https://arxiv.org/abs/1710.10903
   
10) Yedinak, J. L., Li, Y., Krieger, M. S., Howe, K., Daley Ndoye, C., Lee, H., Civitarese, A. M., Marak, T., Nelson, E., Samuels, E. A., Chan, P. A., Bertrand, T., & Marshall, B. D. L. (2021). Machine learning takes a village: Assessing neighbourhood-level vulnerability for an overdose and infectious disease outbreak. International Journal of Drug Policy, 96, 103395.

11) Yokoyama, H., & Takefuji, Y. (2026). Unbiased evaluation of social vulnerability: A multimethod approach using machine learning and nonparametric statistics. Cities, 168, 106519.

12) Zhao, Y., Paul, R., Reid, S., Coimbra Vieira, C., Wolfe, C., Zhang, Y., & Chunara, R. (2024). Constructing social vulnerability indexes with increased data and machine learning highlight the importance of wealth across global contexts. Social Indicators Research, 175, 639–657.
 

# Appendix

1) Github Repository: https://github.com/AnhJoe/Real-Time_IoT_2022_Quantized_Auto_Encoder

2) U.S. SVI Publications and Use Cases / SUIT Database: https://www.atsdr.cdc.gov/place-health/php/svi/svi-publications.html


# Team Contributions

Joe Nguyen: 

- Project research, report outline, intro, conclusion

- EDA, MLP baseline

- Proofreading

- Quarto setup, report rendering

Haesung Becker:

- Project research

- GCN + GraphSage

- Proofreading

- Github repo setup

Jared Lyon:

- Evaluation pipeline

- GAT

- Proofreading

- Github repo cleanup

We worked closely together to recommend datasets and project ideas related to our interests. After initial inspections, we voted and collectively decided on this experiment and its scope.