project:
  type: book
  output-dir: outputs/reports

book:
  title: "Spatial Multi-Task Graph Neural Network for U.S. County Social Vulnerability Modeling"
  author: "UC Irvine/Statistical Methods: Joe Nguyen, Jared Lyon, Haesung Becker"
  chapters:
    - index.qmd
    - notebooks\01_eda.qmd
    - notebooks\02_baseline_mlp.qmd
    - notebooks\03_gcn.qmd
    - notebooks\04_conclusion.qmd
format:
  pdf:
    output-file: rt_iot_final_report.pdf
    fig-path: outputs/figures
    fontsize: 8pt
    fig-width: 2
    fig-height: 2
    tbl-pos: "htbp"
    dpi: 300
    number-sections: true
    toc: true
    toc-depth: 3
    df-print: default
    keep-tex: true
    geometry:
    - margin=0.75in
    header-includes:
      - \KOMAoption{captions}{tableheading}
      - \usepackage{textcomp}
    include-in-header:
      text: |
        \usepackage[section]{placeins}
        \usepackage{multirow}
        \usepackage{booktabs}
        \usepackage{adjustbox}

execute:
  echo: false
  warning: false
  message: false
  freeze: false
    